const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Tilemap,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.UnloadAudioByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.PlayAtObjectByName,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{cetvelboolen: 0},
	{cetvel: 0},
	{kalemboolean: 0},
	{dogrukalem: 0},
	{Katı: 0},
	{parsomen1: 0},
	{parsomenacik1: 0},
	{cetvel2: 0},
	{dogrukalem2: 0},
	{parsomen2: 0},
	{parsomenacik2: 0},
	{skorkalem: 0},
	{skorparsomen: 0},
	{skorcetvel: 0},
	{Ara: 0},
	{solpalmiye: 0},
	{DöşemeliArkaplan: 0},
	{sagpalmiye: 0},
	{oncali: 0},
	{onyaprak: 0},
	{Sinüs: 0},
	{tabela: 0},
	{zemin: 0},
	{Platform: 0},
	{ÜzerindeKaydır: 0},
	{Sprite: 0},
	{Klavye: 0},
	{spr_sagok: 0},
	{Fare: 0},
	{Dokun: 0},
	{yanzemin: 0},
	{spr_solok: 0},
	{spr_yukariok: 0},
	{arkaplan: 0},
	{basamak: 0},
	{Ses: 0},
	{Döşeme: 0},
	{MetinGirişi: 0},
	{Sprite2: 0},
	{kalem2bool: 0},
	{kalembool: 0}
];

self.InstanceType = {
	cetvel: class extends self.ISpriteInstance {},
	dogrukalem: class extends self.ISpriteInstance {},
	parsomen1: class extends self.ISpriteInstance {},
	parsomenacik1: class extends self.ISpriteInstance {},
	cetvel2: class extends self.ISpriteInstance {},
	dogrukalem2: class extends self.ISpriteInstance {},
	parsomen2: class extends self.ISpriteInstance {},
	parsomenacik2: class extends self.ISpriteInstance {},
	skorkalem: class extends self.ISpriteInstance {},
	skorparsomen: class extends self.ISpriteInstance {},
	skorcetvel: class extends self.ISpriteInstance {},
	solpalmiye: class extends self.ISpriteInstance {},
	DöşemeliArkaplan: class extends self.ITiledBackgroundInstance {},
	sagpalmiye: class extends self.ISpriteInstance {},
	oncali: class extends self.ISpriteInstance {},
	onyaprak: class extends self.ISpriteInstance {},
	tabela: class extends self.ISpriteInstance {},
	zemin: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Klavye: class extends self.IInstance {},
	spr_sagok: class extends self.ISpriteInstance {},
	Fare: class extends self.IInstance {},
	Dokun: class extends self.IInstance {},
	yanzemin: class extends self.ISpriteInstance {},
	spr_solok: class extends self.ISpriteInstance {},
	spr_yukariok: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	basamak: class extends self.ISpriteInstance {},
	Ses: class extends self.IInstance {},
	Döşeme: class extends self.ITilemapInstance {},
	MetinGirişi: class extends self.ITextInputInstance {},
	Sprite2: class extends self.ISpriteInstance {}
}